### ISSUE TITLE
Separate libs?

### ISSUE THREAD

**Issue by shama** [shama/bel#10]
Hey @maxogden! You mentioned breaking into separate libs. Would that look something like this?

`bel` just creates elements and use `morphdom` or `diffhtml` to update:

```js
var bel = require('bel')
var morphdom = require('morphdom')

function render (text) {
  return bel`<div>${text}</div>`
}
var element = render('hello')

// ... later ...

morphdom(element, render('changed'))
```

@nrn also mentioned this too in #9. That would make `bel` just return pure HTML elements. It doesn't necessarily encourage data down but one could still choose to follow that pattern with the above setup.

**Comment by nrn** [comment]
Yeah, the important thing to me is the createElement function. I'll use it with hyperx when i'm working with something kinda like a template partial, or with https://www.npmjs.com/package/instyled when I want a reusable component with built in styling and simple behavior (once I get around to PRing the ability to change the createElement function), or even directly when i'm building DOM from a complex data structure. Sometimes I won't use it if I just have a static html string.

Then I'll dump the results of the above into probably a thin wrapper around morphdom (for now, unless something similar comes up that fits my needs better).

**Comment by maxogden** [comment]
@shama yea I like the morphom composition in your example. Do you think you can also do the same with the dom-css/hyperx moduless, or would that make it significantly less convenient to use?

**Comment by shama** [comment]
The easiest way for `dom-css` is to just remove it and we would do:

```js
var bel = require('bel')
var css = require('dom-css')
var div = bel`<div>hello</div>`
css(div, {color: 'red'})
```

Which is only slightly less convenient. I'm not a huge fan of inline styles anyways so this feature isn't super important to me. I prefer to write CSS in a template string and setting an unique class on my modules 👉 https://github.com/shama/bel/wiki/CSS-Modules

---

As for hyperx, it would become:

```js
var hyperx = require('hyperx')
var bel = hyperx(require('bel'))
var div = bel`<div>hello</div>`
```

Which isn't too bad and would mean we could use hyperxify until or instead of #7.

At that point, this library becomes an alternative to [hyperscript](https://www.npmjs.com/package/hyperscript). So maybe a better strategy is to work on parity and just use hyperscript?

**Comment by shama** [comment]
Or maybe not... looking at the source of hyperscript, it's doing a bit more things.

**Comment by maxogden** [comment]
I'm curious what some of the examples in the bel readme/wiki would look like in this "composable style". On the one hand it'd be nice to have composability to avoid frameworkiness, on the other it might be too many things to compose at once (making it less convenient).

**Comment by shama** [comment]
I'll convert some of the elements I've got in progress now and see how much of a pain it is.

**Comment by shama** [comment]
Done. Please use https://github.com/maxogden/yo-yo for a more full feature set.

**Comment by jbucaran** [comment]
@shama Hi!!

At the time of this writing, yo-yo basically exports bel and tweak morphodom behavior a bit (ah, and events too). So, anyway, I was wondering if there was any chance you could bring dom--css back or at least provide a way for users to specify their own.

If that's out of the question, then, how could `bel` be wrapped (without having to fork / modify it directly) in another tag function that does copy styles?

**Comment by shama** [comment]
@jbucaran You can still use `dom-css` as it works with any native element:

```js
var el = bel`<button>push me</button>`
domCSS(el, { border: '1px solid #000' })
```
