### ISSUE TITLE
BR requires space before closing slash

### ISSUE THREAD

**Issue by vorg** [shama/bel#107]
Trying to create `<br/>` tag crashes with `InvalidCharacterError (DOM Exception 5): The string contains invalid characters.` both in Safari and Chrome. Removing slash or adding a space before it fixes the problem. It looks like bel is trying to create "br/" element and fails.

```
var bel = require('bel')
console.log(bel`<p>a <br> b</p>`) // ok
console.log(bel`<p>a <br /> b</p>`) // ok
console.log(bel`<p>a <br/> b</p>`) // error
```

**Comment by yoshuawuyts** [comment]
Hey yeah, sorry about that. It's a known limitation of the parsing engine; we should probably fix that sometime soon. Thanks for reporting!
