### ISSUE TITLE
Issue on hosting bundled JavaScript code on gh-pages or surge.sh

### ISSUE THREAD

**Issue by fraserxu** [shama/bel#11]
Hi I'm sorry this issue might not be a bug of bel but I got a issue while trying to host a static page to gh-pages.

I'm pushing the bundled code to gh-pages branch with a npm module called [gh-pages](https://www.npmjs.com/package/gh-pages). The code looks fine on the [gh-pages branch](https://github.com/fraserxu/videos/tree/gh-pages) of the repo, but while visiting the gh-page [url](http://fraserxu.me/videos/), I got the following error from Chrome devtools

<img width="1679" alt="screen shot 2016-03-13 at 9 48 53 pm" src="https://cloud.githubusercontent.com/assets/1183541/13728238/73b7f742-e965-11e5-8d98-ec5146528351.png">

I did a few debug and find this line on gh-pages branch is https://github.com/fraserxu/videos/blob/gh-pages/bundle.js#L44 

```JavaScript
var SVGNS = 'http://www.w3.org/2000/svg'
var BOOL_PROPS = {
  autofocus: 1,
  checked: 1,
  defaultchecked: 1,
  disabled: 1,
  formnovalidate: 1,
  indeterminate: 1,
  readonly: 1,
  required: 1,
  willvalidate: 1
}
```

but when opening the page and checking from Chrome debug tools [the script](https://fraserxu.me/videos/bundle.js) becomes to 

```JavaScript
var SVGNS = 'http:var BOOL_PROPS={autofocus:1,checked:1,defaultchecked:1,disabled:1,formnovalidate:1,indeterminate:1,readonly:1,required:1,willvalidate:1}
```

I have no idea why is breaking on gh-pages, the code works perfectly fine on my local though.

I also tried to push the same code to a tool called [surge.sh](http://surge.sh/) but [the code](http://videos.fraserxu.me/bundle.js) is the same as on gh-pages.

Sorry again that this is not really a bug with bel but you may have any idea with this problem?

**Comment by shama** [comment]
Whoa that is weird. Let me try on a fork.

**Comment by shama** [comment]
I forked your repo, ran `npm i` and `./deploy.sh` and it appears to work for me http://shama.github.io/videos/

Maybe just a github gh-pages deploy hiccup?

**Comment by fraserxu** [comment]
@shama Thanks for helping trying it out. I did try to remove the gh-pages branch and do a fresh build, but the result it still the same.

Could it be something related to **JavaScript comment** as `//www.w3.org/2000/svg` in the code is removed somehow from `var SVGNS = 'http://www.w3.org/2000/svg'`?

I tried to change the source code from node_modules directory of bel and change it to use double quote. This could fix the issue but I got a new error 

> Uncaught Error: unhandled:8

<img width="1680" alt="screen shot 2016-03-14 at 10 35 38 am" src="https://cloud.githubusercontent.com/assets/1183541/13732202/9711e3d6-e9d0-11e5-9af7-bd82215e9901.png">

Which is caught from https://github.com/shama/videos/blob/gh-pages/bundle.js#L288 by [hyperx](https://github.com/substack/hyperx/blob/master/index.js#L115)

<img width="1680" alt="screen shot 2016-03-14 at 10 37 09 am" src="https://cloud.githubusercontent.com/assets/1183541/13732206/d41c7bec-e9d0-11e5-865d-00949d03484a.png">


Again, the same code works fine from my local :(

**Comment by fraserxu** [comment]
I did dig into the code more and trying to debug from the source code of `hyperx` and I managed to fix the issue by changing the syntax to 

```JavaScript
var bel = require('bel')

module.exports = function (opts) {
  opts = opts || {}
  var width = opts.width || 480
  var styles = opts.styles || ''

  var controls = !opts.controls
  var poster = opts.poster || ''

  // add quotes to attribute value
  var mp4Src = opts.mp4Src ? bel`<source src='${opts.mp4Src}' type="video/mp4">` : ''
  var oggSrc = opts.oggSrc ? bel`<source src='${opts.oggSrc}' type="video/ogg">` : ''
  var webmSrc = opts.webmSrc ? bel`<source src='${opts.webmSrc}' type="video/webm">` : ''

  // add quotes to attribute value
  return bel`<video width='${width}' style='${styles}' controls='${controls}' poster='${poster}'>
    ${mp4Src}
    ${oggSrc}
    ${webmSrc}
    Your browser doesn't support HTML5 video tag.
  </video>`
}

``` 

The difference is that whether attribute value is surrounded by quotes.

I'm not sure whether this is by design from `hyperx`or is something that @substack might missing? I'm afraid not as it always works on my local but not `gh-pages` or `surge.sh` ¯\_(ツ)_/¯

**Comment by fraserxu** [comment]
Also, from the example given on hypex, the attribute value for an event handler is written like this without quotes

```JavaScript
<button onclick=${onclick}>click me!</button>
```

**Comment by fraserxu** [comment]
Thanks @shama for the help! I'm closing this "issue" now and will update back here if I find out what causing this.
