### ISSUE TITLE
.toString()?

### ISSUE THREAD

**Issue by yoshuawuyts** [shama/bel#13]
Perhaps it would be cool to include a proper `.toString()` method - I've found it quite useful when debugging in other packages. Right now it has the following behavior:

```js
const bel = require('bel')
const tree = bel`<div>hello world</div>`
console.log(tree.toString())
// => <div></div>
```

Thanks!

Similar to https://github.com/shama/base-element/issues/5

**Comment by shama** [comment]
I played trying to implement this a bit. We are using `min-document` which should do this but doesn't traverse into child nodes for some reason. Might just be a bug.

In the meantime I've been using `electron` to generate server side HTML: https://github.com/shama/dontkry.com/blob/yo-yo/build.js#L65

**Comment by chromakode** [comment]
Re: child node traversal, I noticed that text nodes weren't working this afternoon. The issue there is that bel expects text nodes to have a [nodeName](https://github.com/shama/bel/blob/master/index.js#L104) set, which in browsers is `'#text'`, but in min-document this is currently unset.

I've opened a pull request on min-document to add this: https://github.com/Raynos/min-document/pull/37

**Comment by chromakode** [comment]
Looks like a [similar change](https://github.com/chromakode/min-document/commit/eaa5b6c88555df2c50a666c98f55f57d258c4c4c) to min-document is needed for element nodes. @shama, is the check for `nodeName` necessary? If you removed it from bel I think you could get child node stringifying working without needing changes upstream.

**Comment by shama** [comment]
Oh sweet! Thanks for digging into @chromakode! No it's probably not needed. I just added two checks to be sure it was a dom node.

**Comment by yoshuawuyts** [comment]
:tada:
