### ISSUE TITLE
Remove `global` dependency?

### ISSUE THREAD

**Issue by feross** [shama/bel#14]
What is the `global` dependency used for? Is it just used to get a reference to `window.document`, or does it help this to work in the Node.js environment?

```
└─┬ yo-yo@1.1.1
  ├─┬ bel@4.1.0
  │ ├─┬ global@4.3.0
  │ │ ├─┬ min-document@2.18.0
  │ │ │ └── dom-walk@0.1.1
  │ │ └── process@0.5.2
  │ └─┬ hyperx@2.0.2
  │   └── hyperscript-attribute-to-property@1.0.0
  └── morphdom@1.1.2
```

Would be nice if we could reduce this tree to:

```
└─┬ yo-yo@1.1.1
  ├─┬ bel@4.1.0
  │ └─┬ hyperx@2.0.2
  │   └── hyperscript-attribute-to-property@1.0.0
  └── morphdom@1.1.2
```

**Comment by feross** [comment]
Otherwise, great work on this package!

**Comment by yoshuawuyts** [comment]
> or does it help this to work in the Node.js environment?

Yup, it's to render on the server. See #13

**Comment by feross** [comment]
Got it. No problem. Looks like it's excluded by `global`'s package.json "browser" field anyway. But it'll still get installed for my electron app. No worries.

**Comment by yoshuawuyts** [comment]
> so it won't add to browserify bundle size

Wasn't aware `global` did that; that's heaps good!

In order to get `browserify` fields working in `electron`, this thread might be interesting https://github.com/atom/electron/issues/1574#issuecomment-173024468

**Comment by shama** [comment]
Thanks @feross and @yoshuawuyts!
