### ISSUE TITLE
Wiki out of date?

### ISSUE THREAD

**Issue by nichoth** [shama/bel#17]
The wiki says `bel` does diffing, but it looks like it only creates elements and `morphdom` is used to diff and update?

> bel is a simple element creator. It returns pure DOM elements but still uses efficient DOM diffing to 
> update.

**Comment by maxogden** [comment]
yes that is correct, morphdom used to be a dependency but it no longer is

**Comment by shama** [comment]
I'll update the wiki now.

**Comment by shama** [comment]
Updated thanks @nichoth!
