### ISSUE TITLE
Injecting strings with HTML content

### ISSUE THREAD

**Issue by ungoldman** [shama/bel#18]
Is it possible to inject ~~raw~~ a HTML string into a bel element? Right now I can't seem to get that working.

Example:

```
var bel = require('bel')
var html = '<div>hi</div>'
var body = bel`<div>${html}</div>`

document.body.appendChild(body)

try {
  document.body.appendChild(bel`${html}`)
} catch (e) {
  document.body.appendChild(bel`<div>${e.message}</div>`)
}
```

Output:

```
<div>&lt;div&gt;hi&lt;/div&gt;</div>
<div>Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.</div>
```

http://requirebin.com/?gist=b7081814ea6465115d84

---

I'm trying to get this working for [`friends`](https://github.com/moose-team/friends/) (trying out a rewrite of the front-end using `yo-yo`). Old method was to convert the html to a vdom element but that doesn't apply in this instance since ain't no vdom around. Here's the part that's causing the issue in friends if you're curious: https://github.com/moose-team/friends/blob/master/lib/elements/messages.js#L44-L58

**Comment by fraserxu** [comment]
Hi @ungoldman I've tried to do the same thing as well when I tried to make a markdown component. 

> You can [use with/without hyperx](https://github.com/shama/bel#use-withwithout-hyperx) 

```JavaScript
var yo = require('yo-yo')
var marked = require('marked')

module.exports = function (source, opts) {
  if (opts) {
    marked.setOptions(opts)
  }

  // create an empty container
  var container = document.createElement('span')
  // use innerHTML to set the content
  container.innerHTML = marked(source)

  return yo`${container}`
}
```

The idea is to use `innerHTML` to convert the `String` to `HTML`.

React has a similar api called [dangerouslySetInnerHTML](https://facebook.github.io/react/tips/dangerously-set-inner-html.html)

```JavaScript
function createMarkup() { return {__html: 'First &middot; Second'}; };
<div dangerouslySetInnerHTML={createMarkup()} />
```

Not sure whether this is the best way to do it but that's what I've got so far, hope this could help. :D

**Comment by shama** [comment]
Yep! If you want to inject HTML unescaped use `innerHTML`:

```js
var bel = require('bel')
var body = bel`<div></div>`
body.innerHTML = '<div>hi</div>'
```

Or if it needs to be further down embedded, create a placeholder element:

```js
var content = bel`<div></div>`
content.innerHTML = '<strong>hi!</strong>'
var body = bel`<div>
  <h3>heading</h3>
  ${content}
</div>`
```

Just be aware, if any user supplied content is going into the `innerHTML`, be sure to escape those values first.

**Comment by fraserxu** [comment]
Is this one a good option for the use case here? [sanitize-html](https://www.npmjs.com/package/sanitize-html)

**Comment by ungoldman** [comment]
Thanks, that makes a lot of sense. :100:

**Comment by ungoldman** [comment]
@fraserxu in the project I'm working on we're already sanitizing it elsewhere but I would say that would definitely be useful in this context :)

**Comment by ungoldman** [comment]
Note: might be worth mentioning this in the readme, @shama let me know if that makes sense and I'll send a PR

**Comment by fraserxu** [comment]
@shama Do you think it's a good idea to create a simple component that use `sanitize-html` to do this easily?

### Code

```JavaScript
var yo = require('yo-yo')
var sanitizeHtml = require('sanitize-html')

module.exports = function (source) {
  // create an empty container
  var container = document.createElement('span')
  // use innerHTML to set the content
  container.innerHTML = sanitizeHtml(source)

  return yo`${container}`
}
```

### API

```JavaScript
var element = elementWrapper(htmlString)
```

### Usage

```JavaScript
var yo = requrie('yo-yo')
var elementWrapper = require('element-wrapper')

var htmlString = '<div>dangerously set html</div>'
var app = yo`${elementWrapper(htmlString)}`

document.body.appendChild(app)
```

**Comment by shama** [comment]
@ungoldman A PR would be great! Thanks!

@fraserxu We get native HTML escaping with template strings, so ```yo`${htmlString}```` would yield the same escaped result. I run into needing unescaped HTML and sanitization most often with i18n:

```js
var locale = {
  msg: 'A reminder email has been sent to <strong>{email}</strong>.'
}
function t (key, data) {
  var translation = locale[key]
  Object.keys(data).forEach(function (opt) {
    var val = sanitizeHTML(data[opt])
    translation = translation.replace(new RegExp('{' + opt + '}', 'g'), val)
  })
  return translation
}

// Got some input from a user
var email = 'my@email.com'
var banner = yo`<div class="banner"></div>`
banner.innerHTML = t('msg', { email: email })

// Add the banner to the page
var page = yo`<div class="page">${banner}</div>`
```

That way I'm sure that all potential user entered input is sanitized before going into an `innerHTML`. So when I need to sanitize heavily depends on what the app is doing.

**Comment by ungoldman** [comment]
I didn't notice the wiki at all until after opening the last couple issues -- sorry! I opted for creating a new wiki page: https://github.com/shama/bel/wiki/Working-with-HTML
