### ISSUE TITLE
Support for virtual-dom style object

### ISSUE THREAD

**Issue by ungoldman** [shama/bel#19]
Is it reasonable to expect the same kind of support for style objects as in `hyperx`? I'd like to be able to do the following but this seems to only work with `hyperx` & `virtual-dom/h` at the moment.

```js
var bel = require('bel')
var style = { color: 'red' }
var el = bel`<div style=${style}>`
console.log(el)
// <div style="[object Object]"></div>
```

> see also https://github.com/substack/hyperx/issues/3

**Comment by ungoldman** [comment]
Ah just saw https://github.com/shama/bel/issues/15#issuecomment-197501150, closing this issue as it looks like it was already discussed and using something like `dom-css` is preferred.

**Comment by shama** [comment]
Yep! Now I just put the call to `dom-css` on another line:
```js
var bel = require('bel')
var domcss = require('dom-css')

var el = bel`<div>Hello</div>`
domcss(el, { color: 'red' })
```
