### ISSUE TITLE
SVG namespace

### ISSUE THREAD

**Issue by nichoth** [shama/bel#21]
Error with xmlns attribute.

``` html
<svg width="150" height="100" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 3 2">
      <rect width="1" height="2" x="0" fill="#008d46" />
 </svg>
```

see #22

**Comment by shama** [comment]
Thanks! I'll take a look. FWIW, the `xmlns` attribute isn't required as bel will detect if an SVG tag and apply the proper namespace. Otherwise, a namespace can be applied with `namespace="http://someplace.com"`

**Comment by nichoth** [comment]
Yes, I've been just deleting the xmlns attribute and it works fine. Programs like illustrator include it by default, so it would be nice to parse them.

**Comment by serapath** [comment]
just ran into the same thing. Removing worked :-) thx
