### ISSUE TITLE
SVG -- :"Error: multiple root elements must be wrapped in an enclosing tag"

### ISSUE THREAD

**Issue by nichoth** [shama/bel#23]
Getting this error with SVG. I also had this issue with some self closing tags in HTML:

```html
<!-- throws -->
<img src=""></img>

<!-- ok -->
<img src="">
```

See PR #24 for failing test.

If no one knows how to fix this, I will try tomorrow if I have time.

**Comment by shama** [comment]
The `img` tag says: `Must have a start tag and must not have an end tag.`
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

So `<img src="">` or `<img src="" />` is what should be used.

**Comment by nichoth** [comment]
True about the image example, but it's still an issue though — when I try this example svg from [Mozilla](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feMerge) it throws.

```html
    <svg width="200" height="200"

      <filter id="feOffset" x="-40" y="-20" width="100" height="200">
          <feOffset in="SourceGraphic" dx="60" dy="60" />
          <feGaussianBlur in="SourceGraphic" stdDeviation="5" />
          <feMerge>
              <feMergeNode in="blur2" />
              <feMergeNode in="SourceGraphic" />
          </feMerge>
      </filter>

      <rect x="40" y="40" width="100" height="100"
       style= "stroke : #000000; fill: green; filter: url(#feOffset);" />
      <rect x="40" y="40" width="100" height="100"
        style= "stroke : #000000; fill: green; " />
    </svg>

```

**Comment by shama** [comment]
It looks like that MDN example needed some help and we had an incorrect self closing tag on hyperx. I sent a PR to indicate that `feMerge` isn't self closing: https://github.com/substack/hyperx/pull/24 and cleaned up the example on MDN.

**Comment by nichoth** [comment]
Thanks @shama ! Yes it works after I delete `feMerge` from hyperx.
