### ISSUE TITLE
How to handle text with html tags

### ISSUE THREAD

**Issue by kvnneff** [shama/bel#29]
For example, from an api I might receive some text:

`{ story: '<p>Some story</p>' }`

When I put that through bel (actually choo.view):

```js
bel`<div>${story}</div>`
```

I get:

`<div><p>Some story</p></div>`

But the `<p></p>` is just plain text, and not a dom element.  I feel like others must have run across this and there's something obvious I'm missing.

I created a requirebin to demonstrate: http://requirebin.com/?gist=d3ac1f22ff3acbd63a1113ddcf560583

**Comment by fraserxu** [comment]
You can refer to the wiki on working with HTML https://github.com/shama/bel/wiki/Working-with-HTML

```js
var sanitizeHTML = require('sanitize-html')
content.innerHTML = 'The user said: ' + sanitizeHTML(userMessage)
```

**Comment by timwis** [comment]
You can pass the string through bel to belify it.

`var text = html('<p>Some text</p>')`

[demo](http://requirebin.com/?gist=1b0c313ab90c5dbf7e5ecc584a7dc789)

**Comment by kvnneff** [comment]
Excellent, thank you!
