### ISSUE TITLE
[idea] pseudo inline styles

### ISSUE THREAD

**Issue by shama** [shama/bel#3]
An idea for handling CSS:

```js
var bel = require('bel')
var css = {
  position: 'absolute',
  top: 100,
  left: 200
}
var element = bel`<div style=${css}>Hello!</div>`
```

Which would detect the `style` key and use [dom-css](https://www.npmjs.com/package/dom-css) to set the `.style[prop]` directly on the elements (CSP safe). It will even do vendor prefixing.

**Comment by tunnckoCore** [comment]
@shama @yoshuawuyts could we revive that by adding really few bytes?

Very basic and almost enough support for this can be implemented in 2-4 lines

```js
      // support style as object
      // both `fontSize` and `font-size` work that way
      if (key === 'style' && typeof p === 'object') {
        for (var k in p) {
          el.style[k] = p[k]
        }
        continue
      }
```

The cool thing is that DOM is smart enough, so it accepts `el.style.fontSize` and `el.style['font-size']` by default.

**Comment by shama** [comment]
```js
var bel = require('bel')
var css = require('dom-css')
var element = bel`<div>Hello!</div>`
css(element, {
  position: 'absolute',
  top: 100,
  left: 200
})
```

Is pretty much the same code but then you can control which version of `dom-css` you use or even use an entirely different CSS library. It's not about implementation difficultly but rather keeping this library generic.

**Comment by timwis** [comment]
That starts to be a lot less convenient when `element` is a tree and you want to style its children though. You'd have to use `querySelector` and such. :-/

**Comment by shama** [comment]
Maybe it's because I rarely use inline styles and when I do, it's almost always directly on the element. Non-inline CSS is far superior IMO so this convenience isn't useful to me.

But, if the overwhelming consensus is to add this back then we can.

**Comment by tunnckoCore** [comment]
Probably. But it cost nothing and DOM itself supports it. If anyone want more then he can use something like `dom-css` or such.

**Comment by yoshuawuyts** [comment]
Agree with @shama. Yeah, also wouldn't use this, but not opposed tho if
people want it. It would need to be ported to yo-yoify and tested on both
projects before we could land it
