### ISSUE TITLE
lifecycle hooks

### ISSUE THREAD

**Issue by yoshuawuyts** [shama/bel#30]
As per [our twitter convo](https://twitter.com/shamakry/status/746016373030084608) we should probably investigate the possibilities of adding lifecycle hooks to `yo-yo` / `bel` again :sparkles:

**Comment by shama** [comment]
I want to play around with how this will affect the ecosystem but I'm thinking we should implement as custom events for consistency with existing events:

```js
var popover = bel`<div onload=${function () {
  document.addEventListener('mousedown', isMouseOutside, false)
}} onunload=${function () {
  document.removeEventListener('mousedown', isMouseOutside, false)
}}>hi</div>`

// Fire onload
document.body.appendChild(popover)

// Fire onunload
document.body.removeChild(popover)
```

I only chose the names `onload` and `unload` to correspond with the native event names on `window`.

---

Also atm I just want to stick with these two events. Each framework has an analog to these two, so when implementing interoperability later it will make it easy if we don't add any more custom events like [`onresize`](https://github.com/shama/resize-event) or `onbeforeunload` etc.

**Comment by yoshuawuyts** [comment]
ooh, yeah I really like that - means that there's no overhead unless explicitly opted in to. Might perhaps need some work with `yo-yoify` on that, but I think this would def be the right approach!

Yeah, also think that sticking to these two events would be good. Might be worth considering to pass the enclosing element as the first argument to the callback for `onload` so that any stuff like `d3` can just attach itself to the node instead of having to do some odd hoop jumping to find the node it should append itself to. What do you reckon?

**Comment by timwis** [comment]
@yoshuawuyts the first time I read your comment, I thought you meant pass the _parent_ element (misread "enclosing"). Reading it again, I think you meant the element itself (that probably makes more sense anyway). Right?

```javascript
return bel`<div class="map" onload=${(el) => L.map(el)}></div>`
```
Because without a reference to it, you'd have to memoize the element, which could get a bit tedious. Unless `this` already references the element.

**Comment by yoshuawuyts** [comment]
@timwis yup, you got that right - apologies for not being clear enough
