### ISSUE TITLE
Rules around unescaping ascii sequences

### ISSUE THREAD

**Issue by josephg** [shama/bel#35]
I'm trying to include raw html, including `&lt;`:

If do `&lt;` it gets double-escaped:
```javascript
> bel`<div>&lt;</div>`.toString()
'<div>&amp;lt;</div>'
```

But if I just put a raw `<` in bel gets super confused:
```javascript
> bel`<div><</div>`.toString()
'<div>&lt;/div</div>'
```

This seems to work for my use case:
```javascript
> bel`<div>${'<raw>'}</div>`.toString()
'<div>&lt;raw&gt;</div>'
```

.. But I only figured that out by guessing. What are the rules around escaping / unescaped literal HTML strings?

**Comment by jmeas** [comment]
[This wiki page](https://github.com/shama/bel/wiki/Working-with-HTML) could be useful.

**Comment by josephg** [comment]
Ah - thanks. I opened the wiki but didn't see that page. I'm nervous that `<div>${'<'}</div>` will stop working at some point, but I guess the library is a bit too young to worry at the moment. Cheers!

**Comment by jmeas** [comment]
:v:

**Comment by shama** [comment]
FWIW, I think it would be good to revisit later. Where sequences (`&nbsp;` and `&amp;`) get encoded as commonly expected with hyperx.

Also maybe eventually providing syntax to unescaped expressions, maybe something like:

```js
var safelyPrecompiled = '<strong>hi!</strong>'
var el = bel`<div>$${safelyPrecompiled}</div>`
```
