### ISSUE TITLE
Comments in template strings throw errors

### ISSUE THREAD

**Issue by toddself** [shama/bel#41]
``` js
bel`<div>
<!-- this is a comment -->
</div>`
```

Throws an `InvalidCharacterError` since you can't create an HTML comment via `createElement` (but can through `createComment`).

It would be awesome if bel either ignored comments or created them.

Happy to create a PR for either scenario

**Comment by jamen** [comment]
I think creating them would be more useful for things outside of bel that might use comments in some way.

**Comment by shama** [comment]
It looks like [hyperx](https://github.com/substack/hyperx) doesn't parse comments yet, we'd probably need to start there for adding support.

This is what we get now with the comment `<!-- testing -->`:
<img width="870" alt="screen shot 2016-08-24 at 5 26 52 pm" src="https://cloud.githubusercontent.com/assets/99604/17952520/0e95fb48-6a20-11e6-8731-22960d2cc362.png">

**Comment by toddself** [comment]
It would be possible, for now, to skip `!--` tags while support is worked on for hyperx?

**Comment by shama** [comment]
I think if we had a function that would adequately skip comments, we could use that function to support comments. :)

**Comment by toddself** [comment]
:laughing: you've got a good point there!

i'll see what i can do with hyperx...

**Comment by tornqvist** [comment]
I've just submitted a pull request to hyperx with added support for comments: https://github.com/substack/hyperx/pull/44
I've also prepared a branch with support in bel: https://github.com/tornqvist/bel/tree/feature/comments

**Comment by jbucaran** [comment]
Awesome! Hope this gets merged soon 👍
