### ISSUE TITLE
shouldComponentUpdate for impure DOM nodes

### ISSUE THREAD

**Issue by markbrown4** [shama/bel#50]
Can you include leaf nodes inside bel components that don't get blown away on re-renders?

```js
const dataVizBiz = (state, prev, send) => {
  function load(el) {
    d3.select(el)
      .selectAll('div')
      .data([4, 8, 15, 16, 23, 42])
      .enter()
      .append('div')
      .style('height', (d)=> d + 'px')
  }

  return html`
    <div onload=${load}></div>
  `
}
```

Similar to React's `shouldComponentUpdate=${() => false}` it would nice to have a way to be able to add an element on first render, but allow it to persist on re-renders without being touched.  Would be great if we can pass data in `onupdate` to modify the DOM too.

```html
<div onload=${load} onupdate=${update} leaf></div>
```

Here's the complete example I'm trying to get working with Choo.
https://github.com/markbrown4/choo-demo/blob/master/7-friends.js

**Comment by markbrown4** [comment]
**Edit** This issue is probably at the wrong level, I was able to get the example above working by setting morphdom's `isSameNode` to true to prevent re-renders.

**Comment by yoshuawuyts** [comment]
feel like nested `isSameNode` instances would achieve what you're proposing, am I right?
