### ISSUE TITLE
img.onload shadowed; maybe should be documented

### ISSUE THREAD

**Issue by coreytrampe** [shama/bel#57]
I just want to document a little user story wrt the `onload` event. I'm new to choo / bel, and wanted to fade in some images after loading. So I added a `load` event handler to an image, like this:

```javascript
html`<img onload=${imgLoaded} src=${small} srcset=${sources}></img>`
```

And then in the handler, at first I was expecting a 'normal' `onload` event:

```javascript
const imgLoaded = e => e.target.style.opacity = 1
```

And when I found that `e.target` was `undefined`, I logged out `e` and discovered that it was actually the image object. "Oh... unwrapped for convenience? OK cool, let's continue..."

```javascript
const imgLoaded = img => img.style.opacity = 1
```

And of course, that didn't start the fadein after image load, but immediately. I flailed for awhile. I had no idea what was going on. I searched, I played around, and I spent an embarrassing about of time trying to figure it out, and ended up writing this:

```javascript
const imgLoaded = img => {
    const wait = () => {
      if (img.complete)
        img.style.opacity = 1
      else
        requestAnimationFrame(wait)
    }
    requestAnimationFrame(wait)
  }
```

Which gave me the desired behavior, but at unnecessary cost. I was glad it was 'working', and all... but called it a day with this horrible nagging feeling. And then... *in the middle of the night*, I woke up and realized what was actually going on. (Thanks, subconscious!) So I wrote this:

```javascript
const imgLoaded = img =>
  console.log(img.onload) // DOH!
```

And finally, this:

```javascript
const imgLoaded = img =>
  img.onload = () => // like, for reals
    img.style.opacity = 1
```

Yay. Let's document this, okay?

Thanks 😄

**Comment by shama** [comment]
`onload` and `onunload` are documented here: https://github.com/shama/bel#lifecycle-events If you have any suggestions on better documenting those lifecycle events please feel free to send a PR. Thanks!

**Comment by coreytrampe** [comment]
Fair enough. I did read that section, but only after I was in the weeds. Now that I'm reading it again, it seems pretty obvious.

Oh, well. Maybe this issue will help someone else later on, boarding the choo train.
