### ISSUE TITLE
[question] Should .update() become .outerHTML ?

### ISSUE THREAD

**Issue by shama** [shama/bel#6]
Would adding `.outerHTML` as a setter to update the element be a good idea? Might make it feel more native.

**Comment by maxogden** [comment]
IMO that would make it feel too magic to me, cause I would think it was an actual DOM method and not something that you provide

**Comment by shama** [comment]
Yep, I agree. Thanks!

**Comment by nrn** [comment]
Glad you didn't go this way :)
