### ISSUE TITLE
bel/on-load: allow for multiple onload/unload events?

### ISSUE THREAD

**Issue by greghuc** [shama/bel#60]
Hi there,

This is more of a question than a bug, and affects [bel](https://github.com/shama/bel) and [on-load](https://github.com/shama/on-load) together.

I'm writing a tiny framework where:
* views are generated with `yo/bel`
* the framework implements "view load/unload" hooks with an `on-load` call on the generated view

The problem I'm having is that the framework's `on-load` call will override any prior onload/onunload attributes set within the `yo/bel` view:

```
//View supplied to framework
view = yo`<div onload=${c('view load')} onunload=${c('view unload')}>page1</div>`;

//Frameword sets up view load/unload hooks
onLoad(view, c('framework load'), c('framework unload'));

function c (value) {
    return function() {
        console.log(value);
    }
}

document.body.appendChild(view)

//Output is 'framework load', not 'view load'
```

Any advice on how to handle this? Ideally, I'd like all onload/onunload functions (supplied by both view and framework) to fire, order irrelevant.

I dug through the `bel` and `on-load` code and discovered:
* `bel`: when creating the view in DOM form, `bel` makes the appropriate `on-load` calls for any onload/onunload attributes specified. But there isn't any easy way to get access to the onload/onunload functions that were added (e.g. to wrap/call them from the framework)
* `on-load`: I believe only one onload/onunload function-pair can be associated with a DOM element. I wondered if I could associate multiple pairs by running multiple instances of `on-load`, each with their own `data-onloadid` attribute. However this is not possible, as `require('on-load')` would point to the same library.

This hasn't been an issue for the [choo](https://github.com/yoshuawuyts/choo) framework so far, as I believe a choo view is expected to [handle onload/onunload behaviour](https://github.com/yoshuawuyts/choo#view--requirechoohtmlhtml), and not the choo framework (so not both).

Any advice appreciated :-)

Greg

**Comment by yoshuawuyts** [comment]
Yeah ran into this also - think we should find a way to allow for multiple
onload handlers to be set on a single element hey

**Comment by greghuc** [comment]
Closing, as bel no longer supports on-load
