### ISSUE TITLE
Transform to convert template strings to document calls

### ISSUE THREAD

**Issue by shama** [shama/bel#7]
Unfortunately `bel` doesn't work with [hyperxify](https://www.npmjs.com/package/hyperxify) but I think we could write a transform that goes even further.

Where it converts:

```js
var title = 'hello'
var element = bel`<div><h1>${title}</h1></div>`
```

into:

```js
var title = 'hello'
var element = (function (p1) {
  var e0 = document.createElement('div')
  var e1 = document.createElement('h1')
  var t0 = document.createTextNode(p1)
  e1.appendChild(t0)
  e0.appendChild(e1)
  return e0
}(title))
```

Then we support older browsers and get a significant performance boost.

We could move the hyperx function into it's own library that outputs this stack. In here, it create elements. In the transform, it would create javascript strings.

**Comment by shama** [comment]
Done! https://github.com/shama/yo-yoify

Brings the perf from `~23ms per loop` to `~17ms per loop` and could get a bit more efficient (I was just taking too long to finish it). It also makes this all compatible with older browsers.

**Comment by chromakode** [comment]
:rocket:
