### ISSUE TITLE
[Question] How bel attachs events to an element?

### ISSUE THREAD

**Issue by thiamsantos** [shama/bel#75]

**Comment by goto-bus-stop** [comment]
[By setting the `on*` properties on the element.](https://github.com/shama/bel/blob/5b0d458bb21ccb29cedf57cb6838825dc9a4802b/browser.js#L84-L85)

```js
var el = bel`
  <div onclick=${handler} />
`
// is equivalent to
var el = document.createElement('div')
el.onclick = handler
```

**Comment by thiamsantos** [comment]
I can't believe that's just it! Thanks @goto-bus-stop
