### ISSUE TITLE
export createElement

### ISSUE THREAD

**Issue by nrn** [shama/bel#8]
bel is a super neat idea!

Is there a way to export the function that is passed into hyperx so that it can be used with other libraries in the ecosystem that work with createElement functions?

**Comment by shama** [comment]
Yep! In [this branch](https://github.com/shama/bel/tree/svg) I'm working on breaking out the compiler to accommodate #7. So it will either return an element or each of the calls needed to create that element.

**Comment by nrn** [comment]
Interesting! I think what I want is the other side though. Instead of using bel to call another createElement function, I want to use another library to call bel's createElement.

**Comment by shama** [comment]
I'm not 100% on the interface but it will likely be:

```js
var createElement = require('bel/create')()
var element = createElement('div', { className: 'testing' }, [
  createElement('h1', {}, 'hello')
])
```

and then for raw code:

```js
var createElement = require('bel/create')({ raw: true })
var arrayOfCallsToGenerateThisElement = createElement('div', { className: 'testing' }, [
  createElement('h1', {}, 'hello')
])
```

Would one of those work?

**Comment by nrn** [comment]
Perfect, the first case is exactly what i'm looking for.

**Comment by shama** [comment]
With `v3.0.0` you can now do:

```js
var bel = require('bel/create')()
var element = bel('div', { className: 'test' }, [
  bel('h3', {}, ['hello!'])
])
document.body.appendChild(element)
```

**Comment by nrn** [comment]
Awesome, thank you!
