### ISSUE TITLE
exporting non-dist javascript via raw.js

### ISSUE THREAD

**Issue by graforlock** [shama/bel#90]
People typically don't want to compile their node_modules and it then makes it problematic in terms of the standard approach and filesize. For example, at this point:

```javascript
 function browser () {
    var el = bel`<div></div>`
    el.innerHTML = tag
    return toArray(el.childNodes)
  }
```

IE11 will just throw exception in this uncompiled scenario.

**Comment by bcomnes** [comment]
cc @jondashkyle

**Comment by jondashkyle** [comment]
@bcomnes @graforlock just double checking that the pull request covers this one?

https://github.com/shama/bel/pull/92

**Comment by graforlock** [comment]
yeah we can close that.
